//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSystem.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Т {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Т() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EduSystem.Common.Т", typeof(Т).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        public static string ForgotPasswordLinkText {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkText", resourceCulture);
            }
        }
        
        public static string RegisterLinkText {
            get {
                return ResourceManager.GetString("RegisterLinkText", resourceCulture);
            }
        }
        
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        public static string PasswordPlaceholderText {
            get {
                return ResourceManager.GetString("PasswordPlaceholderText", resourceCulture);
            }
        }
        
        public static string EmailPlaceholderText {
            get {
                return ResourceManager.GetString("EmailPlaceholderText", resourceCulture);
            }
        }
        
        public static string EmailIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        public static string PasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        public static string PasswordIsDifferentThanConfirmedErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsDifferentThanConfirmedErrorMessage", resourceCulture);
            }
        }
        
        public static string EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholderText", resourceCulture);
            }
        }
        
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        public static string LoginLinkText {
            get {
                return ResourceManager.GetString("LoginLinkText", resourceCulture);
            }
        }
        
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        public static string SendResetRequestButtonText {
            get {
                return ResourceManager.GetString("SendResetRequestButtonText", resourceCulture);
            }
        }
        
        public static string IRememberedMyPasswordLinkText {
            get {
                return ResourceManager.GetString("IRememberedMyPasswordLinkText", resourceCulture);
            }
        }
    }
}
